apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  namespace: demo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      containers:
        - name: demo-web
          image: docker.io/hashicorp/http-echo:1.0.0
          args:
            - "-text=hello-from-demo-web"
          ports:
            - containerPort: 5678
